version: "3.9"
services:  
  debezium-connect:
    image: debezium/connect
    ports:
      - "8083:8083"
    networks: 
      - zk
    environment:
      GROUP_ID: 1
      BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      CONFIG_STORAGE_TOPIC: debezium-connect-configs
      OFFSET_STORAGE_TOPIC: debezium-connect-offsets
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  zk:
    external: true